#
# PaintSHOP Pipeline Run Configuration -- pipeline version v1.2
#

########################################################################
#
#  REQUIRED PARAMETERS
#
########################################################################

# input file paths
assembly: 'mm10'
genome_fasta: 'data/mm10.fa'
annotation_file: 'data/mm10.refGene.gtf'

########################################################################
#
#  OPTIONAL PARAMETERS (uncomment parameters to override defaults)
#
########################################################################

# blockparse params (initial probe candidate mining)
# blockparse_min_length: 30
# blockparse_max_length: 37 # 30
# blockparse_min_tm: 42
# blockparse_max_tm: 47 
# 65-72 our setting -- different tool (what else is going on in the solution)
# run this

# 2
# 50%
# 24 = 37 + 0.65(*30) - 0.65(*50)

# number of threads for bowtie2 to use
# bowtie2_threads: 4

# the temperature at which you want to predict probe hybridization with XGBoost
# current options are: 37, 42, 47, 52, 60
# model_temp: 42
# match with min_tm??? or 57???

# NUPACK 4 model specification https://piercelab-caltech.github.io/nupack-docs/model/#model-specification
# nupack_material: 'dna' #### uncertain
# nupack_ensemble: 'stacking'
nupack_celsius: 57 # smaller number could be more strigent # formamide adjusted** # 74.5
nupack_sodium: 0.30 # 0.39
# nupack_magnesium: 0.0

# OPTIONAL: it is possible to provide already designed DNA-FISH probes to the pipeline
# and then run downstream steps, including thermodynamic, specifity, and secondary
# structure analysis, as well as intersection with the genome annotations file to yield
# RNA probe sets. If the `existing_probes` option is left commented out in this file, de
# novo probes will be generated. If the `existing_probes` option is uncommented here, the
# path to a BED file with DNA probes with columns [chrom, start, stop, seq] must be provided.
# existing_probes: 'data/test_probes.bed'

# OPTIONAL: it is possible to skip particular chromosomes during probe design. Chromosomes
# specified here will be excluded from probe design but still included in the bowtie2 index
# for the accuracy of alignment and off-target predictions of all probes. NOTE: the values
# specified here must match the fasta sequence header values (e.g. 'chr1' ) exactly
# exclude_chroms:
#   - chrM
